sudo: required

language: ruby

addons:
  chrome: stable

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script: bundle exec rspec spec

env:
  matrix:
    - RAILS=5.2.0 AA=1.4.0
    - RAILS=5.2.0 AA=2.0.0
    - RAILS=6.0.0 AA=2.6.0

rvm:
  - 2.5
  - 2.6
